export const CHANGE_VIEW_STYLE = 'CHANGE_VIEW_STYLE'
export const TOGGLE_LOADING_SIGN = 'TOGGLE_LOADING_SIGN'
export const SEARCH_CONFIRM = 'SEARCH_CONFIRM'
export const SET_TOP_PICKS = 'SET_TOP_PICKS'

